### ISSUE TITLE
Use slug package

### ISSUE THREAD

**Issue by simison** [talha-asad/mongoose-url-slugs#17]
Hey! Thanks for this plugin.

I'm relying to [slug](https://www.npmjs.com/package/slug) package since it handles nicely a lot of edge cases.

``` javascript
var slug = require('slug'),
      URLSlugs = require('mongoose-url-slugs'),;

TagSchema.plugin(URLSlugs('label', {
  field: 'slug',
  generator: slug
}));
```

Perhaps you could simply use it internally as well? It's very similar to your custom solution already.

Thoughts / PR welcome?

**Comment by talha-asad** [comment]
That package has extensive options, however i am not sure if we should depend/internally use it.
A `URLSlugs.default.generator` might be handy for people who choose to use it throughout their project.

**Comment by talha-asad** [comment]
On a second thought I think we should use that package. I would merge a PR for that.

**Comment by simison** [comment]
Yup. Actually I've been comparing a few of these libraries. While slug package is nice, it doesn't seem to be maintained anymore (https://github.com/dodo/node-slug/issues/32#issuecomment-213521254).

Looking at https://github.com/pid/speakingurl now.

**Comment by talha-asad** [comment]
Closing, you can always use it wherever you want through the option.
