### ISSUE TITLE
Module stops on empty slug

### ISSUE THREAD

**Issue by twm213** [talha-asad/mongoose-url-slugs#24]
The slug becomes empty when the text is empty or when its contains entirely foreign characters. It slugifies to an empty string, therefore doesn't get past this point.

```
if (!newSlug.length && options.index_sparse) {
    doc.set(options.field, undefined);
    return next();
}
```

Perhaps there can be a fallback such as returning an empty separator, e.g. "-"?

**Comment by talha-asad** [comment]
Yes that, or an incrementing number could work, I'll accept a PR for this. I will not be able to contribute to this project for a little while.

**Comment by talha-asad** [comment]
This is not an issues anymore, if you still see this problem, provide a reproduction.
