### ISSUE TITLE
Saving "undefined" if slug field is not selected

### ISSUE THREAD

**Issue by nikpundik** [talha-asad/mongoose-url-slugs#33]
Hi,
I've recently updated to 1.0.0 and found this problem.

In these situations:

```
MyModel
 .findOne()
 .select('justOneField')
 .then(myRecord => myRecord.save())
```

the slug property gets set to "undefined"

**Comment by talha-asad** [comment]
@nikpundik This has been fixed in the latest release and a test has been added, sorry it took me a while to get to this. Thanks for reporting.
