### ISSUE TITLE
It adds a number to the end when it's not necessary

### ISSUE THREAD

**Issue by dassennato** [talha-asad/mongoose-url-slugs#34]
Hi,

I'm using 1.0.0 and consider this case:
```javascript
const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const URLSlugs = require('mongoose-url-slugs');

let fooSchema = new Schema({
    name: { type: String, required: true },
});

fooSchema.plugin(URLSlugs('name'));

const Foo = mongoose.model('Foo', fooSchema);

Foo.create({
    name: 'Foo Bar'
})
.then((foo) => {
    console.log(foo.slug); // ====> 'foo-bar', this slug is ok!
    return Foo.create({
        name: 'Foo'
    });
})
.then((foo) => {
    console.log(foo.slug); // ====>'foo-2' was created but 'foo' was expected.
});

```
If I invert the order, I first create 'Foo' and then 'Foo Bar' it works as expected.

Thanks!

**Comment by talha-asad** [comment]
hey @dassennato,

Seems you've found a bug, I would dig into this further over the week, in the meanwhile if you find a solution, please don't hesitate to submit a PR.

Thanks!

**Comment by dassennato** [comment]
Thanks for the reply. I could start working in a PR but, to be honest, I'm still playing around with other similar libraries in order to know which library suits best to me.
Another problem I'm facing with this library it's that it strictly uses `mpromise` and it doesn't allow to use ES6 promises doing `mongoose.Promise = global.Promise;` 
Do you have plans to allow that feature in the future?

**Comment by ralphnajm** [comment]
I made a fix https://github.com/talha-asad/mongoose-url-slugs/pull/36

**Comment by talha-asad** [comment]
Merged and test added
